### ISSUE TITLE
Item uses shows "Item (Upgrade)" when the action is actually "downgrade"

### ISSUE THREAD

**Issue by gunnaro** [SaulLawliet/MelvorIdleMods#10]
Minor issue I just noticed when looking at item uses for items that are downgrade-able, like perfect cooking food, for example:
![image](https://github.com/SaulLawliet/MelvorIdleMods/assets/1041656/8e61eadf-d58a-4c2b-a2ab-8e32e589b0b5)
The category "Item (Upgrade)" should be "Item (Downgrade)" for those items, as shown in the screenshot.

**Comment by SaulLawliet** [comment]
Thank you for report this. Fixed in v1.0.18
