### ISSUE TITLE
Nightfall Season's Modifier (-50% Astrology Interval) Not Found By the Mod

### ISSUE THREAD

**Issue by Ctumille** [SaulLawliet/MelvorIdleMods#2]
![Astrology](https://github.com/SaulLawliet/MelvorIdleMods/assets/7392476/86d2f9dc-3a9e-47ed-adea-af0d5570b160)

**Comment by SaulLawliet** [comment]
It's fixed now. All township season modifiers will be calculated.
Please restart the game to see.
