### ISSUE TITLE
Show Skill Modifiers: odd error message when viewing preservation chance; possible floating point precision issue? 

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [SaulLawliet/MelvorIdleMods#3]
Hey, thanks for the great work, use a lot of your mods. Finally getting to completing Mastery and as gathering resources DR Potions are a pain in the butt I was checking out the preservation chances when I came across this message:

<div align="center">
<img alt="error" src="https://github.com/SaulLawliet/MelvorIdleMods/assets/3438658/51d52d6a-7cf5-4c20-a8f4-eb3c78bc0344" width="50%" />
</div>

I *think* it's probably some floating point monkey business, which should be pretty easy to fix, but I can't say for sure. If it was then I don't know what the message about sources refers to.

**Comment by SaulLawliet** [comment]
Thank you for report this. It's fixed in v4.3.4 ;)

**Comment by MadeOfMagicAndWires** [comment]
Cheers!
