### ISSUE TITLE
Show Skill Modifiers: icon position conflicts with the new Game Guide icon  

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [SaulLawliet/MelvorIdleMods#4]
Sure you have noticed already, but the skill modifier button element bumps up the Game Guide icon which in turn makes the header move partly out of view.

Example:
![image](https://github.com/SaulLawliet/MelvorIdleMods/assets/3438658/18806012-dc9a-4176-90fc-4f0d3389a53c)

Easiest fix is to move the `button` element outside of its current parent `div` and simply append it after:
![image](https://github.com/SaulLawliet/MelvorIdleMods/assets/3438658/18a2593c-f674-4232-9bbe-92e3262e3c2e)

Still looks a bit wonky, I'll leave it to you if you want to keep the button the same size or whether you want to match the game guide icon, which is a bit too small imo. 

Cheers.

**Comment by SaulLawliet** [comment]
Yeah. Take your suggestion. 🥂
