### ISSUE TITLE
Missing sources in new ancient relic mode.

### ISSUE THREAD

**Issue by georgeRobertson2** [SaulLawliet/MelvorIdleMods#5]
Just a small issue in the new Ancient relic mode where the relic modifiers are missing from the sources.

E.g. I have the +50% Thieving Mastery XP relic in Thieving and it's missing in the sources.
![image](https://github.com/SaulLawliet/MelvorIdleMods/assets/41301972/7dea3556-7af6-4df2-bbf4-6041f054424d)
![image](https://github.com/SaulLawliet/MelvorIdleMods/assets/41301972/b3f88311-3093-424e-a6aa-9ebb938e4a2c)

**Comment by SaulLawliet** [comment]
I'm doing this. Maybe this week.

**Comment by SaulLawliet** [comment]
It has been released in v.5.2.1 ;)
