### ISSUE TITLE
[Show Skill Modifiers]  Slayer Area Effect calculated but not shown

### ISSUE THREAD

**Issue by KumaV1** [SaulLawliet/MelvorIdleMods#6]
Hey, I just found a minor issue, where modifiers coming from a slayer area effect are found and calculated in, displaying in the overview - but if you click on "more", they are not included.

![grafik](https://github.com/SaulLawliet/MelvorIdleMods/assets/146348901/f9a1675a-d6f6-4fb5-9905-1552aa868a8d)

![grafik](https://github.com/SaulLawliet/MelvorIdleMods/assets/146348901/433bcc9e-0a15-4a65-8f43-9dd6386a4ae8)

**Comment by KumaV1** [comment]
Btw, a short other note, if it is not on purpose, I can't set a label for the issue.

**Comment by SaulLawliet** [comment]
Sorry, just saw this issue.
It's fixed in v.5.2.4.
