### ISSUE TITLE
[Show Item Sources And Uses] Usage type "Combat Spells"

### ISSUE THREAD

**Issue by KumaV1** [SaulLawliet/MelvorIdleMods#7]
It might be worth adding combat spells to the list of usages. Currently, only alt-magic processes are recognized and displayed, while combat spells are completely missed out.
![grafik](https://github.com/SaulLawliet/MelvorIdleMods/assets/146348901/e37036d6-eabd-40b6-b80f-010d5956939a)

**Comment by SaulLawliet** [comment]
I don't think this is necessary, like 'Air Rune'.
The list would be too long if we added combat spells.;(

Also, when I play the game, I only use very few spells.

**Comment by KumaV1** [comment]
True, now that you mention air runes and thinking about all the types of spells... those lists would be huge. And pretty much anyone will now the use case of combat in general, so a generic, grouped entry "Combat Spells" is quite redundant as well.
